### ISSUE TITLE
pip install with python2.7 faild

### ISSUE THREAD

**Issue by nakano16180** [elephantrobotics/pymycobot#25]
**Describe the bug**
```
$ pip install -e .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Obtaining file:///home/nakano/python_ws/pymycobot
    ERROR: Command errored out with exit status 1:
     command: /home/nakano/python_ws/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/nakano/python_ws/pymycobot/setup.py'"'"'; __file__='"'"'/home/nakano/python_ws/pymycobot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-OgVc7V
         cwd: /home/nakano/python_ws/pymycobot/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/nakano/python_ws/pymycobot/setup.py", line 12, in <module>
        import pymycobot
      File "pymycobot/__init__.py", line 7, in <module>
        from pymycobot.mycobot import MyCobot
      File "pymycobot/mycobot.py", line 7, in <module>
        import serial
    ImportError: No module named serial
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
**To Reproduce**
1. clone this repository
2. cd ./pymycobot/
3. pip install -e .

**Expected behavior**
installed pymycobot without error

**Screenshots**
![Screenshot from 2021-09-20 18-26-37](https://user-images.githubusercontent.com/36945685/134513051-ca7107fd-5438-413f-98af-f5b689702b15.png)

**Comment by anla-xu** [comment]
It has been repaired. Thank you for your feedback.
